Movie_Assignment/MovieCoreMVCUI/Controllers/TheaterController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Configuration;
using Movie_Entity;
using Newtonsoft.Json;
using System.Collections.Generic;
using System.Net.Http;
using System.Text;
using System.Threading.Tasks;

namespace MovieCoreMVCUI.Controllers
{
    public class TheaterController : Controller
    {
        IConfiguration _configuration;
        public TheaterController(IConfiguration configuration)
        {
            _configuration = configuration;
        }
        public async Task <IActionResult> Index()
        {
            IEnumerable<Theater> theaterresult = null;
            using (HttpClient client = new HttpClient())
            {

                string endPoint = _configuration["WebApiBasedUrl"] + "Theater/GetTheater";
                using (var response = await client.GetAsync(endPoint))
                {
                    if (response.StatusCode == System.Net.HttpStatusCode.OK)
                    {
                        var result = await response.Content.ReadAsStringAsync();
                        theaterresult = JsonConvert.DeserializeObject<IEnumerable<Theater>>(result);
                    }


                }
            }
            return View(theaterresult);

        }

          
        

        public IActionResult TheaterEntry()
        {
            return View();
        }
      
        [HttpPost]
        public async Task<IActionResult> TheaterEntry(Theater theater)

        {
            using (HttpClient client = new HttpClient())
            {
                StringContent content = new StringContent(JsonConvert.SerializeObject(theater), Encoding.UTF8, "application/json");
                string endPoint = _configuration["WebApiBasedUrl"] + "Theater/AddTheater";
                using (var response = await client.PostAsync(endPoint, content))
                {
                    if (response.StatusCode == System.Net.HttpStatusCode.OK)
                    {
                        ViewBag.status = "Ok";
                        ViewBag.message = "Theater details saved successfully";
                    }
                    else
                    {
                        ViewBag.status = "Error";
                        ViewBag.message = "Wrong Entries";
                    }
                }
            }
            return View();
        }
        public async Task<IActionResult> EditTheater(int TheaterId)
        {
            Theater theater = null;
            using (HttpClient client = new HttpClient())
            {
                string endPoint = _configuration["WebApiBasedUrl"] + "Theater/GetTheaterByID?theaterId=" + TheaterId;



                using (var response = await client.GetAsync(endPoint))
                {
                    if (response.StatusCode == System.Net.HttpStatusCode.OK)
                    {
                        var result = await response.Content.ReadAsStringAsync();
                        theater = JsonConvert.DeserializeObject<Theater>(result);
                    }

                }
            }
            return View(theater);
        }

        [HttpPost]
        public async Task<IActionResult> EditTheater(Theater theater)

        {
            using (HttpClient client = new HttpClient())
            {
                StringContent content = new StringContent(JsonConvert.SerializeObject(theater), Encoding.UTF8, "application/json");
                string endPoint = _configuration["WebApiBasedUrl"] + "Theater/UpdateTheater";
                using (var response = await client.PutAsync(endPoint, content))
                {
                    if (response.StatusCode == System.Net.HttpStatusCode.OK)
                    {
                        ViewBag.status = "Ok";
                        ViewBag.message = "Theater details updated successfully";
                    }
                    else
                    {
                        ViewBag.status = "Error";
                        ViewBag.message = "Wrong Entries";
                    }
                }
            }
            return View();
        }


        public async Task<IActionResult> DeleteTheater(int TheaterId)
        {
            Theater theater = null;
            using (HttpClient client = new HttpClient())
            {
                string endPoint = _configuration["WebApiBasedUrl"] + "Theater/GetTheaterById?theaterId=" + TheaterId;

                using (var response = await client.GetAsync(endPoint))
                {
                    if (response.StatusCode == System.Net.HttpStatusCode.OK)
                    {
                        var result = await response.Content.ReadAsStringAsync();
                        theater= JsonConvert.DeserializeObject<Theater>(result);
                    }

                }
            }
            return View(theater);
        }

        [HttpPost]
        public async Task<IActionResult> DeleteTheater(Theater theater)

        {
            using (HttpClient client = new HttpClient())
            {

                string endPoint = _configuration["WebApiBasedUrl"] + "Theater/DeleteTheater?tid=" + theater.Id;
                using (var response = await client.DeleteAsync(endPoint))
                {
                    if (response.StatusCode == System.Net.HttpStatusCode.OK)
                    {
                        ViewBag.status = "Ok";
                        ViewBag.message = "Theater details deleted successfully";
                    }
                    else
                    {
                        ViewBag.status = "Error";
                        ViewBag.message = "Wrong Entries";
                    }
                }
            }
            return View();
        }

    }
}

Movie_Assignment/MovieCoreMVCUI/Views/Theater/DeleteTheater.cshtml
@model Movie_Entity.Theater;

<div>
    <a asp-controller="Theater" asp-action="Index">Index</a>

</div>

<form method="post" enctype="multipart/form-data">
    <h2>Theater Entry</h2><hr />

    <h2>Theater Entry</h2><hr />
    <div class="form-group">
        <label>Theater ID</label>
        <input type="text" asp-for="Id" class="form-control"
               placeholder="enter Theater id" required />
    </div>
    <div class="form-group">
        <label>Theater Name</label>
        <input type="text" asp-for="Name" class="form-control"
               placeholder="enter Theater name" required />
    </div>
    <div class="form-group">
        <label>Movie Type</label>
        <input type="text" asp-for="Address" class="form-control"
               placeholder="enter Address" required />
    </div>

    <input type="submit" value="Delete" class="btn btn-outline-success" />
    <input type="button" value="Reset" class="btn btn-outline-secondary" />
    <hr />
    @if (ViewBag.Status == "Ok")
    {
        <div class="alert alert-success">
            @ViewBag.message;
        </div>
    }

    else if (ViewBag.Status == "Error")
    {
        <div class="alert alert-danger">
            @ViewBag.message;
        </div>
    }
</form>

Movie_Assignment/MovieCoreMVCUI/Views/Theater/EditTheater.cshtml
@model Movie_Entity.Theater;

<div>
    <a asp-controller="Theater" asp-action="Index">Index</a>

</div>

<form method="post" enctype="multipart/form-data">
    <h2>Theater Entry</h2><hr />

    <h2>Theater Entry</h2><hr />
    <div class="form-group">
        <label>Theater ID</label>
        <input type="text" asp-for="Id" class="form-control"
               placeholder="enter Theater id" required />
    </div>
    <div class="form-group">
        <label>Theater Name</label>
        <input type="text" asp-for="Name" class="form-control"
               placeholder="enter Theater name" required />
    </div>
    <div class="form-group">
        <label>Movie Type</label>
        <input type="text" asp-for="Address" class="form-control"
               placeholder="enter Address" required />
    </div>

    <input type="submit" value="Save" class="btn btn-outline-success" />
    <input type="button" value="Reset" class="btn btn-outline-secondary" />
    <hr />
    @if (ViewBag.Status == "Ok")
    {
        <div class="alert alert-success">
            @ViewBag.message;
        </div>
    }

    else if (ViewBag.Status == "Error")
    {
        <div class="alert alert-danger">
            @ViewBag.message;
        </div>
    }
</form>

Movie_Assignment/MovieCoreMVCUI/Views/Theater/Index.cshtml
@model IEnumerable<Movie_Entity.Theater>

<div>
    <a asp-controller="Theater" asp-action="TheaterEntry">Theater Entry</a>

</div>

<div class="row">
    <div class="col-12 ">
        <h3>Theater's</h3>
        <hr />
        <table class="table table-light table-bordered table-hover">
            <thead>
                <tr>
                    <th>Theater Id</th>
                    <th>Theater Name</th>
                    <th>Theater Address</th>
                    <th>Edit</th>
                    <th>Delete</th>
                </tr>
            </thead>
            <tbody>
                @foreach (var theater in Model)
                {
                    <tr>
                        <td>@theater.Id</td>
                        <td>@theater.Name</td>
                        <td>@theater.Address</td>
                    
                        <td><a asp-controller="Theater" asp-action="EditTheater" asp-route-TheaterId=@theater.Id>Edit</a></td>
                        <td><a asp-controller="Theater" asp-action="DeleteTheater" asp-route-TheaterId=@theater.Id>Delete</a></td>
                    </tr>
                }
        </table>
    </div>

</div>

Movie_Assignment/MovieCoreMVCUI/Views/Theater/TheaterEntry.cshtml
@model Movie_Entity.Theater;

<div>
    <a asp-controller="Theater" asp-action="Index">Index</a>

</div>

<form method="post" enctype="multipart/form-data">
    <h2>Theater Entry</h2><hr />
    <div class="form-group">
        <label>Theater Name</label>
        <input type="text" asp-for="Name" class="form-control"
               placeholder="enter Theater name" required />
    </div>
    <div class="form-group">
        <label>Theater Address</label>
        <input type="text" asp-for="Address" class="form-control"
               placeholder="enter Address" required />
    </div>
  
    <input type="submit" value="Save" class="btn btn-outline-success" />
    <input type="button" value="Reset" class="btn btn-outline-secondary" />
    <hr />
    @if (ViewBag.Status == "Ok")
    {
        <div class="alert alert-success">
            @ViewBag.message;
        </div>
    }

    else if (ViewBag.Status == "Error")
    {
        <div class="alert alert-danger">
            @ViewBag.message;
        </div>
    }
</form>