Movie_Assignment/MovieCoreMVCUI/Controllers/BookingController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Configuration;
using Movie_Entity;
using Newtonsoft.Json;
using System.Collections.Generic;
using System.Net.Http;
using System.Text;
using System.Threading.Tasks;

namespace MovieCoreMVCUI.Controllers
{
    public class BookingController : Controller
    {
        IConfiguration _configuration;
        public BookingController(IConfiguration configuration)
        {
            _configuration = configuration;
        }

        public async Task <IActionResult> Index()
        {
            IEnumerable<Booking> bookingresult = null;
            using (HttpClient client = new HttpClient())
            {

                string endPoint = _configuration["WebApiBasedUrl"] + "Booking/GetBooking";
                using (var response = await client.GetAsync(endPoint))
                {
                    if (response.StatusCode == System.Net.HttpStatusCode.OK)
                    {
                        var result = await response.Content.ReadAsStringAsync();
                        bookingresult = JsonConvert.DeserializeObject<IEnumerable<Booking>>(result);
                    }


                }
            }
            return View(bookingresult);
        }
        public IActionResult BookingEntry()
        {
            return View();
        }
        [HttpPost]
        public async Task<IActionResult> BookingEntry(Booking booking)

        {
            using (HttpClient client = new HttpClient())
            {
                StringContent content = new StringContent(JsonConvert.SerializeObject(booking), Encoding.UTF8, "application/json");
                string endPoint = _configuration["WebApiBasedUrl"] + "Booking/AddBooking";
                using (var response = await client.PostAsync(endPoint, content))
                {
                    if (response.StatusCode == System.Net.HttpStatusCode.OK)
                    {
                        ViewBag.status = "Ok";
                        ViewBag.message = "Booking details saved successfully";
                    }
                    else
                    {
                        ViewBag.status = "Error";
                        ViewBag.message = "Wrong Entries";
                    }
                }
            }
            return View();
        }

        public async Task<IActionResult> EditBooking(int bookingId)
        {
           Booking booking = new Booking();
            using (HttpClient client = new HttpClient())
            {
                string endPoint = _configuration["WebApiBasedUrl"] + "Booking/GetBookingByID?bookingId=" + bookingId;



                using (var response = await client.GetAsync(endPoint))
                {
                    if (response.StatusCode == System.Net.HttpStatusCode.OK)
                    {
                        var result = await response.Content.ReadAsStringAsync();
                        booking = JsonConvert.DeserializeObject<Booking>(result);
                    }

                }
            }
            return View(booking);
        }

        [HttpPost]
        public async Task<IActionResult> EditUser(Booking booking)

        {
            using (HttpClient client = new HttpClient())
            {
                StringContent content = new StringContent(JsonConvert.SerializeObject(booking), Encoding.UTF8, "application/json");
                string endPoint = _configuration["WebApiBasedUrl"] + "Booking/UpdateBooking";
                using (var response = await client.PutAsync(endPoint, content))
                {
                    if (response.StatusCode == System.Net.HttpStatusCode.OK)
                    {
                        ViewBag.status = "Ok";
                        ViewBag.message = "Booking details updated successfully";
                    }
                    else
                    {
                        ViewBag.status = "Error";
                        ViewBag.message = "Wrong Entries";
                    }
                }
            }
            return View();
        }


        public async Task<IActionResult> DeleteBooking(int bookingId)
        {
           Booking booking = null;
            using (HttpClient client = new HttpClient())
            {
                string endPoint = _configuration["WebApiBasedUrl"] + "Booking/GetBookingByID?bookingId=" + bookingId;

                using (var response = await client.GetAsync(endPoint))
                {
                    if (response.StatusCode == System.Net.HttpStatusCode.OK)
                    {
                        var result = await response.Content.ReadAsStringAsync();
                        booking = JsonConvert.DeserializeObject<Booking>(result);
                    }

                }
            }
            return View(booking);
        }

        [HttpPost]
        public async Task<IActionResult> DeleteBooking(Booking booking)

        {
            using (HttpClient client = new HttpClient())
            {

                string endPoint = _configuration["WebApiBasedUrl"] + "Booking/DeleteBooking?bid=" + booking.Id;
                using (var response = await client.DeleteAsync(endPoint))
                {
                    if (response.StatusCode == System.Net.HttpStatusCode.OK)
                    {
                        ViewBag.status = "Ok";
                        ViewBag.message = "Booking details deleted successfully";
                    }
                    else
                    {
                        ViewBag.status = "Error";
                        ViewBag.message = "Wrong Entries";
                    }
                }
            }
            return View();
        }
    }
}

Movie_Assignment/MovieCoreMVCUI/Controllers/MovieController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Configuration;
using Movie_Entity;
using Newtonsoft.Json;
using System.Collections;
using System.Collections.Generic;
using System.Net.Http;
using System.Text;
using System.Threading.Tasks;

namespace MovieCoreMVCUI.Controllers
{
    public class MovieController : Controller

    {
        IConfiguration _configuration;
        public MovieController(IConfiguration configuration)
        {
            _configuration = configuration;
        }

        [HttpGet]
        public async Task<IActionResult> Index()
        {
            IEnumerable<Movie> movieresult = null;
            using (HttpClient client = new HttpClient())
            {

                string endPoint = _configuration["WebApiBasedUrl"] + "Movie/GetMovies";
                using (var response = await client.GetAsync(endPoint))
                {
                    if (response.StatusCode == System.Net.HttpStatusCode.OK)
                    {
                        var result = await response.Content.ReadAsStringAsync();
                        movieresult = JsonConvert.DeserializeObject<IEnumerable<Movie>>(result);
                    }

                   
                }
            }
            return View(movieresult);
        }

        public IActionResult MovieEntry()

        {

            return View();
        }
        [HttpPost]
        public async Task<IActionResult> MovieEntry(Movie movie)

        {
            using (HttpClient client = new HttpClient())
            {
                StringContent content = new StringContent(JsonConvert.SerializeObject(movie), Encoding.UTF8, "application/json");
                string endPoint = _configuration["WebApiBasedUrl"] + "Movie/AddMovie";
                using (var response = await client.PostAsync(endPoint, content))
                {
                    if (response.StatusCode == System.Net.HttpStatusCode.OK)
                    {
                        ViewBag.status = "Ok";
                        ViewBag.message = "Movie details saved successfully";
                    }
                    else
                    {
                        ViewBag.status = "Error";
                        ViewBag.message = "Wrong Entries";
                    }
                }
            }
            return View();
        }

       
        public async Task<IActionResult> EditMovie(int MovieId)
        {
            Movie movie = null;
            using (HttpClient client = new HttpClient())
            {
                string endPoint = _configuration["WebApiBasedUrl"] + "Movie/GetMovieByID?movieId=" + MovieId;



                using (var response = await client.GetAsync(endPoint))
                {
                    if (response.StatusCode == System.Net.HttpStatusCode.OK)
                    {
                        var result = await response.Content.ReadAsStringAsync();
                        movie = JsonConvert.DeserializeObject<Movie>(result);
                    }
                   
                }
            }
            return View(movie);
        }

        [HttpPost]
        public async Task<IActionResult> EditMovie(Movie movie)

        {
            using (HttpClient client = new HttpClient())
            {
                StringContent content = new StringContent(JsonConvert.SerializeObject(movie), Encoding.UTF8, "application/json");
                string endPoint = _configuration["WebApiBasedUrl"] + "Movie/UpdateMovie";
                using (var response = await client.PutAsync(endPoint, content))
                {
                    if (response.StatusCode == System.Net.HttpStatusCode.OK)
                    {
                        ViewBag.status = "Ok";
                        ViewBag.message = "Movie details saved successfully";
                    }
                    else
                    {
                        ViewBag.status = "Error";
                        ViewBag.message = "Wrong Entries";
                    }
                }
            }
            return View();
        }


        public async Task<IActionResult> DeleteMovie(int MovieId)
        {
            Movie movie = null;
            using (HttpClient client = new HttpClient())
            {
                string endPoint = _configuration["WebApiBasedUrl"] + "Movie/GetMovieByID?movieId=" + MovieId;



                using (var response = await client.GetAsync(endPoint))
                {
                    if (response.StatusCode == System.Net.HttpStatusCode.OK)
                    {
                        var result = await response.Content.ReadAsStringAsync();
                        movie = JsonConvert.DeserializeObject<Movie>(result);
                    }

                }
            }
            return View(movie);
        }

        [HttpPost]
        public async Task<IActionResult> DeleteMovie(Movie movie)

        {
            using (HttpClient client = new HttpClient())
            {
                string endPoint = _configuration["WebApiBasedUrl"] + "Movie/DeleteMovie?movieId=" + movie.Id;
                using (var response = await client.DeleteAsync(endPoint))
                {
                    if (response.StatusCode == System.Net.HttpStatusCode.OK)
                    {
                        ViewBag.status = "Ok";
                        ViewBag.message = "Movie details deleted successfully";
                    }
                    else
                    {
                        ViewBag.status = "Error";
                        ViewBag.message = "Wrong Entries";
                    }
                }
            }
            return View();
        }
    }
}

Movie_Assignment/MovieCoreMVCUI/Views/Booking/BookingEntry.cshtml
@model Movie_Entity.Booking


<div>
    <a asp-controller="Booking" asp-action="Index">Booking</a>

</div>

<form method="post" enctype="multipart/form-data">
    <h2>Booking</h2><hr />
    <div class="form-group">
        <label>Show Id</label>
        <input type="text" asp-for="ShowId" class="form-control"
               placeholder="enter Show Id" required />
    </div>
    <div class="form-group">
        <label>User Id</label>
        <input type="text" asp-for="uid" class="form-control"
               placeholder="enter User Id" required />
    </div>
    <div class="form-group">
        <label>Status</label>
        <input type="text" asp-for="status" class="form-control"
               placeholder="enter status" required />
    </div>
    <div class="form-group">
        <label>Seat</label>
        <input type="text" asp-for="seat" class="form-control"
               placeholder="enter seat" required />
    </div>
    <input type="submit" value="Save" class="btn btn-outline-success" />
    <input type="button" value="Reset" class="btn btn-outline-secondary" />
    <hr />
    @if (ViewBag.Status == "Ok")
    {
        <div class="alert alert-success">
            @ViewBag.message;
        </div>
    }

    else if (ViewBag.Status == "Error")
    {
        <div class="alert alert-danger">
            @ViewBag.message;
        </div>
    }
</form>

Movie_Assignment/MovieCoreMVCUI/Views/Booking/DeleteBooking.cshtml
@model Movie_Entity.Booking


<div>
    <a asp-controller="Booking" asp-action="Index">Index</a>

</div>

<form method="post" enctype="multipart/form-data">
    <h2>Booking</h2><hr />
    <div class="form-group">
        <label>Booking Id</label>
        <input type="text" asp-for="Id" class="form-control"
               placeholder="enter Booking Id" required />
    </div>
    <div class="form-group">
        <label>Show Id</label>
        <input type="text" asp-for="ShowId" class="form-control"
               placeholder="enter Show Id" required />
    </div>
    <div class="form-group">
        <label>User Id</label>
        <input type="text" asp-for="uid" class="form-control"
               placeholder="enter User Id" required />
    </div>
    <div class="form-group">
        <label>Status</label>
        <input type="text" asp-for="status" class="form-control"
               placeholder="enter status" required />
    </div>
    <div class="form-group">
        <label>Seat</label>
        <input type="text" asp-for="seat" class="form-control"
               placeholder="enter seat" required />
    </div>
    <input type="submit" value="Delete" class="btn btn-outline-success" />
    <input type="button" value="Reset" class="btn btn-outline-secondary" />
    <hr />
    @if (ViewBag.Status == "Ok")
    {
        <div class="alert alert-success">
            @ViewBag.message;
        </div>
    }

    else if (ViewBag.Status == "Error")
    {
        <div class="alert alert-danger">
            @ViewBag.message;
        </div>
    }
</form>

Movie_Assignment/MovieCoreMVCUI/Views/Booking/EditBooking.cshtml
@model Movie_Entity.Booking


<div>
    <a asp-controller="Booking" asp-action="Index">Index</a>

</div>

<form method="post" enctype="multipart/form-data">
    <h2>Booking</h2><hr />
    <div class="form-group">
        <label>Booking Id</label>
        <input type="text" asp-for="Id" class="form-control"
               placeholder="enter Booking Id" required />
    </div>
    <div class="form-group">
        <label>Show Id</label>
        <input type="text" asp-for="ShowId" class="form-control"
               placeholder="enter Show Id" required />
    </div>
    <div class="form-group">
        <label>User Id</label>
        <input type="text" asp-for="uid" class="form-control"
               placeholder="enter User Id" required />
    </div>
    <div class="form-group">
        <label>Status</label>
        <input type="text" asp-for="status" class="form-control"
               placeholder="enter status" required />
    </div>
    <div class="form-group">
        <label>Seat</label>
        <input type="text" asp-for="seat" class="form-control"
               placeholder="enter seat" required />
    </div>
    <input type="submit" value="Save" class="btn btn-outline-success" />
    <input type="button" value="Reset" class="btn btn-outline-secondary" />
    <hr />
    @if (ViewBag.Status == "Ok")
    {
        <div class="alert alert-success">
            @ViewBag.message;
        </div>
    }

    else if (ViewBag.Status == "Error")
    {
        <div class="alert alert-danger">
            @ViewBag.message;
        </div>
    }
</form>

Movie_Assignment/MovieCoreMVCUI/Views/Booking/Index.cshtml
@model IEnumerable<Movie_Entity.Booking>
<div>
    <a asp-controller="Booking" asp-action="BookingEntry">Index</a>

</div>

<div>
    <hr />
    <a asp-controller="Movie" asp-action="MovieEntry">Movie Entry</a>
    <hr />
</div>
<div class="row">
    <div class="col-12 ">
        <h3>Movies</h3>
        <hr />
        <table class="table table-light table-bordered table-hover">
            <thead>
                <tr>
                    <th>Movie Id</th>
                    <th>Movie Name</th>
                    <th>Movie type</th>
                    <th>Movie Description</th>
                    <th>Edit</th>
                    <th>Delete</th>
                </tr>
            </thead>
            <tbody>
                @foreach (var movie in Model)
                {
                    <tr>
                        <td>@movie.Id</td>
                        <td>@movie.Name</td>
                        <td>@movie.MovieType</td>
                        <td>@movie.MoviesDesc</td>
                        <td><a asp-controller="Movie" asp-action="EditMovie" asp-route-MovieId=@movie.Id>Edit</a></td>
                        <td><a asp-controller="Movie" asp-action="DeleteMovie" asp-route-MovieId=@movie.Id>Delete</a></td>
                    </tr>
                }
        </table>
    </div>

</div>