Movie_Assignment/MovieCoreMVCUI/Controllers/ShowTimingController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Configuration;
using Movie_Entity;
using Newtonsoft.Json;
using System.Collections.Generic;
using System.Net.Http;
using System.Text;
using System.Threading.Tasks;

namespace MovieCoreMVCUI.Controllers
{
    public class ShowTimingController : Controller
    {

        IConfiguration _configuration;
        public ShowTimingController(IConfiguration configuration)
        {
            _configuration = configuration;
        }
        public async Task<IActionResult> Index()
        {
            IEnumerable<Showtiming> showresult = null;
            using (HttpClient client = new HttpClient())
            {

                string endPoint = _configuration["WebApiBasedUrl"] + "ShowTiming/GetShowtiming";
                using (var response = await client.GetAsync(endPoint))
                {
                    if (response.StatusCode == System.Net.HttpStatusCode.OK)
                    {
                        var result = await response.Content.ReadAsStringAsync();
                        showresult = JsonConvert.DeserializeObject<IEnumerable<Showtiming>>(result);
                    }


                }
            }
            return View(showresult);
        }
        public IActionResult ShowTimingEntry( )
        {
            return View();
        }
        [HttpPost]
        public async Task<IActionResult> ShowTimingEntry(Showtiming showtiming)

        {
            using (HttpClient client = new HttpClient())
            {
                StringContent content = new StringContent(JsonConvert.SerializeObject(showtiming), Encoding.UTF8, "application/json");
                string endPoint = _configuration["WebApiBasedUrl"] + "ShowTiming/AddShowtiming";
                using (var response = await client.PostAsync(endPoint, content))
                {
                    if (response.StatusCode == System.Net.HttpStatusCode.OK)
                    {
                        ViewBag.status = "Ok";
                        ViewBag.message = "Showtiming details saved successfully";
                    }
                    else
                    {
                        ViewBag.status = "Error";
                        ViewBag.message = "Wrong Entries";
                    }
                }
            }
            return View();
        }

       
        public async Task<IActionResult> EditShowtiming(int ShowId)
        {
            Showtiming showtiming = null;
            using (HttpClient client = new HttpClient())
            {
                string endPoint = _configuration["WebApiBasedUrl"] + "ShowTiming/GetShowtimingByID?showId=" + ShowId;

                using (var response = await client.GetAsync(endPoint))
                {
                    if (response.StatusCode == System.Net.HttpStatusCode.OK)
                    {
                        var result = await response.Content.ReadAsStringAsync();
                        showtiming = JsonConvert.DeserializeObject<Showtiming>(result);
                    }

                }
            }
            return View(showtiming);
        }

        [HttpPost]
        public async Task<IActionResult> EditShowtiming(Showtiming showtiming)

        {
            using (HttpClient client = new HttpClient())
            {
                StringContent content = new StringContent(JsonConvert.SerializeObject(showtiming), Encoding.UTF8, "application/json");
                string endPoint = _configuration["WebApiBasedUrl"] + "ShowTiming/UpdateShowtiming";
                using (var response = await client.PutAsync(endPoint, content))
                {
                    if (response.StatusCode == System.Net.HttpStatusCode.OK)
                    {
                        ViewBag.status = "Ok";
                        ViewBag.message = "Showtiming details updated successfully";
                    }
                    else
                    {
                        ViewBag.status = "Error";
                        ViewBag.message = "Wrong Entries";
                    }
                }
            }
            return View();
        }

        public async Task<IActionResult> DeleteShowtiming(int ShowId)
        {
            Showtiming showtiming = null;
            using (HttpClient client = new HttpClient())
            {
                string endPoint = _configuration["WebApiBasedUrl"] + "ShowTiming/GetShowtimingByID?showId=" + ShowId;



                using (var response = await client.GetAsync(endPoint))
                {
                    if (response.StatusCode == System.Net.HttpStatusCode.OK)
                    {
                        var result = await response.Content.ReadAsStringAsync();
                        showtiming = JsonConvert.DeserializeObject<Showtiming>(result);
                    }

                }
            }
            return View(showtiming);
        }

        [HttpPost]
        public async Task<IActionResult> DeleteShowtiming(Showtiming showtiming)

        {
            using (HttpClient client = new HttpClient())
            {
                string endPoint = _configuration["WebApiBasedUrl"] + "ShowTiming/DeleteShowtiming?showId=" + showtiming.Id;
                using (var response = await client.DeleteAsync(endPoint))
                {
                    if (response.StatusCode == System.Net.HttpStatusCode.OK)
                    {
                        ViewBag.status = "Ok";
                        ViewBag.message = "Showtiming details deleted successfully";
                    }
                    else
                    {
                        ViewBag.status = "Error";
                        ViewBag.message = "Wrong Entries";
                    }
                }
            }
            return View();
        }
    }
}

Movie_Assignment/MovieCoreMVCUI/Views/ShowTiming/DeleteShowtiming.cshtml
@model Movie_Entity.Showtiming
<div>
    <a asp-controller="ShowTiming" asp-action="Index">Index</a>

</div>

<form method="post" enctype="multipart/form-data">
    <h2>Show Timing</h2><hr />

    <div class="form-group">
        <label>Show Id</label>
        <input type="text" asp-for="Id" class="form-control"
               placeholder="enter theater id" required />
    </div>
    <div class="form-group">
        <label>Theater Id</label>
        <input type="text" asp-for="TheaterId" class="form-control"
               placeholder="enter theater id" required />
    </div>
    <div class="form-group">
        <label>Movie Id</label>
        <input type="text" asp-for="MovieId" class="form-control"
               placeholder="enter movie id" required />
    </div>
    <div class="form-group">
        <label>ShowTime</label>
        <input type="datetime-local" asp-for="ShowTime" class="form-control"
               placeholder="enter showtime" required />
    </div>
    <input type="submit" value="Delete" class="btn btn-outline-success" />
    <input type="button" value="Reset" class="btn btn-outline-secondary" />
    <hr />
    @if (ViewBag.Status == "Ok")
    {
        <div class="alert alert-success">
            @ViewBag.message;
        </div>
    }

    else if (ViewBag.Status == "Error")
    {
        <div class="alert alert-danger">
            @ViewBag.message;
        </div>
    }
</form>

Movie_Assignment/MovieCoreMVCUI/Views/ShowTiming/EditShowtiming.cshtml
@model Movie_Entity.Showtiming
<div>
    <a asp-controller="ShowTiming" asp-action="Index">Index</a>

</div>

<form method="post" enctype="multipart/form-data">
    <h2>Show Timing</h2><hr />

    <div class="form-group">
        <label>Show Id</label>
        <input type="text" asp-for="Id" class="form-control"
               placeholder="enter show id" required />
    </div>
    <div class="form-group">
        <label>Theater Id</label>
        <input type="text" asp-for="TheaterId" class="form-control"
               placeholder="enter theater id" required />
    </div>
    <div class="form-group">
        <label>Movie Id</label>
        <input type="text" asp-for="MovieId" class="form-control"
               placeholder="enter movie id" required />
    </div>
    <div class="form-group">
        <label>ShowTime</label>
        <input type="datetime-local" asp-for="ShowTime" class="form-control"
               placeholder="enter showtime" required />
    </div>
    <input type="submit" value="Save" class="btn btn-outline-success" />
    <input type="button" value="Reset" class="btn btn-outline-secondary" />
    <hr />
    @if (ViewBag.Status == "Ok")
    {
        <div class="alert alert-success">
            @ViewBag.message;
        </div>
    }

    else if (ViewBag.Status == "Error")
    {
        <div class="alert alert-danger">
            @ViewBag.message;
        </div>
    }
</form>

Movie_Assignment/MovieCoreMVCUI/Views/ShowTiming/Index.cshtml
@model IEnumerable<Movie_Entity.Showtiming>

<div>
    <a asp-controller="ShowTiming" asp-action="ShowTimingEntry">ShowEntry</a>

</div>





<div class="row">
    <div class="col-12 ">
        <h3>ShowTiming's</h3>
        <hr />
        <table class="table table-light table-bordered table-hover">
            <thead>
                <tr>
                    <th>ShowTime Id</th>
                    <th>Movie Id</th>
                    <th>Theater Id</th>
                    <th>Show-Time</th>
                    <th>Edit</th>
                    <th>Delete</th>
                </tr>
            </thead>
            <tbody>
                @foreach (var show in Model)
                {
                    <tr>
                        <td>@show.Id</td>
                        <td>@show.MovieId</td>
                        <td>@show.TheaterId</td>
                        <td>@show.ShowTime</td>

                        <td><a asp-controller="ShowTiming" asp-action="EditShowtiming" asp-route-ShowId=@show.Id>Edit</a></td>
                        <td><a asp-controller="ShowTiming" asp-action="DeleteShowtiming" asp-route-ShowId=@show.Id>Delete</a></td>
                    </tr>
                }
        </table>
    </div>

</div>

Movie_Assignment/MovieCoreMVCUI/Views/ShowTiming/ShowTimingEntry.cshtml
@model Movie_Entity.Showtiming
<div>
    <a asp-controller="ShowTiming" asp-action="Index">Index</a>

</div>

<form method="post" enctype="multipart/form-data">
    <h2>Show Timing</h2><hr />
    <div class="form-group">
        <label>Theater Id</label>
        <input type="text" asp-for="TheaterId" class="form-control"
               placeholder="enter theater id" required />
    </div>
    <div class="form-group">
        <label>Movie Id</label>
        <input type="text" asp-for="MovieId" class="form-control"
               placeholder="enter movie id" required />
    </div>
    <div class="form-group">
        <label>ShowTime</label>
        <input type="datetime-local" asp-for="ShowTime" class="form-control"
               placeholder="enter showtime" required />
    </div>
    <input type="submit" value="Save" class="btn btn-outline-success" />
    <input type="button" value="Reset" class="btn btn-outline-secondary" />
    <hr />
    @if (ViewBag.Status == "Ok")
    {
        <div class="alert alert-success">
            @ViewBag.message;
        </div>
    }

    else if (ViewBag.Status == "Error")
    {
        <div class="alert alert-danger">
            @ViewBag.message;
        </div>
    }
</form>